In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 
## inline is a backend that renders plots as static images inside the notebook output.

In [3]:
df_index=pd.read_csv('economic_index.csv')

In [5]:
df_index.head()

   s_no  year  month  interest_rate  unemployment_rate  index_price
0     0  2017     12           2.75                5.3         1464
1     1  2017     11           2.50                5.3         1394
2     2  2017     10           2.50                5.3         1357
3     3  2017      9           2.50                5.3         1293
4     4  2017      8           2.50                5.4         1256

In [ ]:
## drop unnecessary columns
df_index.drop(columns=['s_no','year','month'],axis=1)

    interest_rate  unemployment_rate  index_price
0            2.75                5.3         1464
1            2.50                5.3         1394
2            2.50                5.3         1357
3            2.50                5.3         1293
4            2.50                5.4         1256
5            2.50                5.6         1254
6            2.50                5.5         1234
7            2.25                5.5         1195
8            2.25                5.5         1159
9            2.25                5.6         1167
10           2.00                5.7         1130
11           2.00                5.9         1075
12           2.00                6.0         1047
13           1.75                5.9          965
14           1.75                5.8          943
15           1.75                6.1          958
16           1.75                6.2          971
17           1.75                6.1          949
18           1.75                6.1          884
19           1.75                6.1          866
20           1.75                5.9          876
21           1.75                6.2          822
22           1.75                6.2          704
23           1.75                6.1          719