##### Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on alone (not the best idea ikr).
- Any other interesting analysis

best practices 
1. preprocessing and cleaning
2. train test split
3. BOW,TFIDF, WORD2VEC
4. Train ML algorithms

In [48]:
import pandas as pd

In [49]:
## load the dataset

data=pd.read_csv('all_kindle_review.csv')

In [50]:
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [51]:
df=data[['reviewText','rating']]

In [52]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [53]:
df.shape

(12000, 2)

In [54]:
## Missing values

df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [55]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [56]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [57]:
### Preprocessing and cleaning

# positive review is 1 and negative review is 0
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

C:\Users\Len\AppData\Local\Temp\ipykernel_29828\1140514144.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

In [58]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [59]:
df['rating'].unique()

array([1, 0])

In [60]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [61]:
## 1. lower all the cases

df['reviewText']=df['reviewText'].str.lower()

C:\Users\Len\AppData\Local\Temp\ipykernel_29828\1694292221.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()

In [62]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [63]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Len\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [64]:

from bs4 import BeautifulSoup

In [65]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\Len\AppData\Local\Temp\ipykernel_29828\3736800740.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
C:\Users\Len\AppData\Local\Temp\ipykernel_29828\3736800740.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
C:\Users\Len\AppData\Local\Temp\ipykernel_29828\3736800740.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
C:\Users\Len\AppData\Local\Temp\ipykernel_29828\3736800740.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
C:\Users\Len\AppData\Local\Temp\ipykernel_29828\3736800740.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

In [66]:

df.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [67]:
## apply lemmatization

from nltk.stem import WordNetLemmatizer

In [68]:
lemmatizer=WordNetLemmatizer()

In [69]:
def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [70]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

C:\Users\Len\AppData\Local\Temp\ipykernel_29828\1959687590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [71]:
df.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [89]:
# Train Test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [90]:
from sklearn.feature_extraction.text import CountVectorizer

bow=CountVectorizer()

X_train_bow=bow.fit_transform(X_train)
X_test_bow=bow.fit(X_test)

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.fit(X_test)

In [93]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow.toarray(),y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf.toarray(),y_train)

In [85]:

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

ValueError: Expected 2D array, got scalar array instead:
array=CountVectorizer().
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [94]:

y_pred_tfidf=nb_model_bow.predict(X_test_tfidf.toarray())

AttributeError: 'TfidfVectorizer' object has no attribute 'toarray'

In [ ]:

confusion_matrix(y_test,y_pred_bow)

In [ ]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

In [ ]:

confusion_matrix(y_test,y_pred_tfidf)

In [ ]:

print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))